/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExportLazyImport = createFileRoute('/export')()

// Create/Update Routes

const ExportLazyRoute = ExportLazyImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/export.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/export': typeof ExportLazyRoute
}

export interface FileRoutesByTo {
  '/export': typeof ExportLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/export': typeof ExportLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/export'
  fileRoutesByTo: FileRoutesByTo
  to: '/export'
  id: '__root__' | '/export'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ExportLazyRoute: typeof ExportLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ExportLazyRoute: ExportLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/export"
      ]
    },
    "/export": {
      "filePath": "export.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
