name: Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:

  # call workflow to sign the plugin first
  sign_plugin:
    name: Sign Plugin
    uses: ./.github/workflows/sign-extension.yml
    secrets: inherit

  # create release then
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: sign_plugin
 
    steps:
      - name: Download Signed Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: plainly-plugin
          path: .

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            plainly-plugin.zxp

